# Generated by Django 5.2.2 on 2025-06-14 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('t_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TestEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('not_attempted', 'Not Attempted')], default='enrolled', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_enrollments', to='login.loginstudent')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='t_dashboard.test')),
            ],
            options={
                'unique_together': {('test', 'student')},
            },
        ),
    ]
